The Nobel Prize has been among the most prestigious international awards since 1901. Each year, awards are bestowed in chemistry, literature, physics, physiology or medicine, economics, and peace. In addition to the honor, prestige, and substantial prize money, the recipient also gets a gold medal with an image of Alfred Nobel (1833 - 1896), who established the prize.

![](Nobel_Prize.png)

The Nobel Foundation has made a dataset available of all prize winners from the outset of the awards from 1901 to 2023. The dataset used in this project is from the Nobel Prize API and is available in the `nobel.csv` file in the `data` folder.

In this project, you'll get a chance to explore and answer several questions related to this prizewinning data. And we encourage you then to explore further questions that you're interested in!

In [183]:
# Loading in required libraries
import pandas as pd
import seaborn as sns
import numpy as np

In [184]:
#Inspect the dataset
df = pd.read_csv('data/nobel.csv')
print(f"Dataset shape: {df.shape}\n")
df.info()
df.head()

Dataset shape: (1000, 18)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   year                  1000 non-null   int64
 1   category              1000 non-null   object
 2   prize                 1000 non-null   object
 3   motivation            912 non-null    object
 4   prize_share           1000 non-null   object
 5   laureate_id           1000 non-null   int64
 6   laureate_type         1000 non-null   object
 7   full_name             1000 non-null   object
 8   birth_date            968 non-null    object
 9   birth_city            964 non-null    object
 10  birth_country         969 non-null    object
 11  sex                   970 non-null    object
 12  organization_name     736 non-null    object
 13  organization_city     735 non-null    object
 14  organization_country  735 non-null    object
 15  death_date            596 non-null    object
 16  death_city            579 non-null    object
 17  death_country         585 non-null    object
dtypes: int64(2), object(16)
memory usage: 140.8+ KB

   year    category  ... death_city death_country
0  1901   Chemistry  ...     Berlin       Germany
1  1901  Literature  ...   Châtenay        France
2  1901    Medicine  ...    Marburg       Germany
3  1901       Peace  ...     Heiden   Switzerland
4  1901       Peace  ...      Paris        France

[5 rows x 18 columns]

In [185]:
#Most commonly awarded gender and birth
top_gender, top_country = df[['sex', 'birth_country']].value_counts().idxmax()

print(f"Most awarded country: {top_country}\nMost awarded gender: {top_gender}")

Most awarded country: United States of America
Most awarded gender: Male

In [186]:
#Decade each winner was born
df['decade'] = (df['year'] // 10) * 10

df[['birth_country', 'year', 'decade']].head()

      birth_country  year  decade
0       Netherlands  1901    1900
1            France  1901    1900
2  Prussia (Poland)  1901    1900
3       Switzerland  1901    1900
4            France  1901    1900

In [187]:
#Decade with highest ratio of US-born Nobel Prize winner
winners_per_decade = df.groupby('decade').size()
usa_winners_per_decade = df[df['birth_country'] == 'United States of America'].groupby('decade').size()
ratio_per_decade =  usa_winners_per_decade/ winners_per_decade
max_decade_usa = int(ratio_per_decade.idxmax())

print(f"Decade with highest ratio of US-born Nobel Prize winner: {max_decade_usa}")

Decade with highest ratio of US-born Nobel Prize winner: 2000

In [188]:
#Highest proportion of female laureates in decade and Nobel Prize category combination
total_combination = df.groupby(['decade', 'category']).size()
female_combination = df[df['sex'] == 'Female'].groupby(['decade', 'category']).size()
female_proportion = female_combination / total_combination
key, val = female_proportion.idxmax()
key = int(key)
max_female_dict = {
    key:val
}

print(f"Dictionary with highest proportion of female winners: {max_female_dict}")

Dictionary with highest proportion of female winners: {2020: 'Literature'}

In [189]:
#First woman to receive a nobel prize
first_woman = df[df['sex'] == 'Female'].sort_values('year').iloc[0]
first_woman_name, first_woman_category = first_woman[['full_name', 'category']]

print(f"The first woman to receive a nobel prize is {first_woman_name} in {first_woman_category} category")

The first woman to receive a nobel prize is Marie Curie, née Sklodowska in Physics category

In [190]:
#Individuals or organizations won more than once
times_won = df[['full_name']].value_counts().reset_index(name='times_won')

twice_or_more = times_won[times_won['times_won'] > 1]
repeat_list = list(twice_or_more['full_name'])
print(f"List of individuals or organizations won more than once:\n{repeat_list}")

List of individuals or organizations won more than once:
['Comité international de la Croix Rouge (International Committee of the Red Cross)', 'Office of the United Nations High Commissioner for Refugees (UNHCR)', 'Frederick Sanger', 'Linus Carl Pauling', 'John Bardeen', 'Marie Curie, née Sklodowska']